--- #YAML:1.0
name: Perl-Critic
version: 0.14
author:
  - Jeffrey Thalhammer <thaljef@cpan.org>
abstract: Critique Perl source code for best-practices
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
